version = 0.1

[default.deploy.parameters]
stack_name = "ResumeVisitorCounterStack"
resolve_s3 = true
s3_prefix = "ResumeVisitorCounterStack"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "DynamoDBTableName=\"ResumeVisitorCounter\""
image_repositories = []
