name: Deploy Serverless Backend (Lambda/API Gateway) 

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'template.yaml' 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' 

      - name: Install SAM CLI
        run: pip install aws-sam-cli 

      - name: Build SAM Application
        run: sam build --template template.yaml 

      - name: Deploy SAM Application
        run: sam deploy --no-confirm-changeset --no-input --stack-name ResumeVisitorCounterStack --region us-east-1 
        env:
          AWS_DEFAULT_REGION: us-east-1 
