name: Deploy Frontend to S3/CloudFront # Name of your workflow, visible in GitHub Actions tab

on:
  push:
    branches:
      - main 
    paths:
      - 'frontend/**' 

jobs:
  deploy:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code 
        uses: actions/checkout@v4 

      - name: Configure AWS credentials 
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 

      - name: Deploy S3 Website 
        run: | 
          # IMPORTANT: Replace 'your-resume-bucket-name' with the exact name of your S3 bucket
          aws s3 sync frontend/ s3://resume.jamesyoum.com --delete --acl public-read

      - name: Invalidate CloudFront Cache 
        run: |
          # IMPORTANT: Replace 'YOUR_CLOUDFRONT_DISTRIBUTION_ID' with your actual CloudFront Distribution ID
          # You can find this in the CloudFront console (e.g., E123ABCDEFGH)
          aws cloudfront create-invalidation --distribution-id E1N1FCY5SHAT70 --paths "/*"